### PR TITLE
feat: conda self hosted uploads and fix deprecation warnings

### PR DESCRIPTION
**Pull request by Krande**
Hey,

this ended up being a bigger PR than originally anticipated. 

@VegarRingdalAibel and @ofschnai Please make sure you test it properly before we merge :)

### CODE REVIEW

**Comment by VegarRingdalAibel** [comment]
@Krande 
Very nice 🥇
I will start testing on Monday   🧑‍🔬🧪 🔧

**Comment by VegarRingdalAibel** [comment]
Looks like its working well when Ive been testing it with my e2e repos

But I see we get this warning, so maybe we should update this too ?
image

**Comment by VegarRingdalAibel** [comment]
Sample of run:
https://github.com/Aibel365/web-e2e-test-action-toolbox/actions/runs/8565957349

Issue:
image

**Comment by VegarRingdalAibel** [comment]
image

Not super important, but
Is there a way we can just set the same as is in the repo ?
So we dont get the warning ?

**Comment by Krande** [comment]
> image
> 
> Not super important, but Is there a way we can just set the same as is in the repo ? So we dont get the warning ?

Done in https://github.com/AibelDevs/action-toolbox/pull/30/commits/162bb230e7d809f09cc104afe7b9bc186fcb9526

**Comment by VegarRingdalAibel** [comment]
@Krande not been able to find any bugs now.
Tried to use it like I do in my projects
@ofschnai can you give it a try on e2e python repo and see if you notice any bugs.

**Review by VegarRingdalAibel — APPROVED** [review]

**Comment by ofschnai** [comment]
Sorry for the delay in testing. I have tested it for regular functionality now, it works to seems fine. I did't find any error.

**Review by ofschnai — APPROVED** [review]
I have tested the workflows with basic functionality and it seems to work fine. I didn't fine any error.

**Comment by Krande** [comment]
Okay. @VegarRingdalAibel and @ofschnai either one of you are free to merge this PR at your leisure :)

**Pull request merged**
